global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: jgroups-demo
    replica: prometheus-1

# Scrape configuration
scrape_configs:
  # Scrape metrics from OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: jgroups-opentelemetry

## Storage configuration
#storage:
#  tsdb:
#    retention.time: 7d
#    retention.size: 1GB
